### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by IleSir** [themightydeity/XposedCodeApp#1]
Can't install. Says "There was a problem while parsing the package."

**Comment by peejii73** [comment]
Hi, same issue with my phone (4.4.4). In the APK minSdkVersion is set to be "21" (aka Lollipop 5.0), maybe it is due to that?

If so, could you please kindly compile a version with lower requirement or is there something needed that exists only in > 5.0..?

**Comment by daitj** [comment]
i have made a new release, it should work on android 4.0.3 and up.

**Comment by peejii73** [comment]
Hi,

some comments.. 

Yes, now it installs nicely on droid 4.4.4. However, at xposed modules view it says that it is of version 1.0, update available etc.. And in download view it shows that version 1.0 is installed, and it offers an "install" button for version 2. Installing will not change the situation.

Then ... RootCloak 1.52 has apps "com.nordea.mobiletoken" and "fi.nordea.mobilebank" on apps list. Hidden commands contain "find" among others... Still the paranoid Codes says I'm rooted :/

I know you are doing this on your free time, and really appreciate if you could have a look at this. I understand completely if you are busy with other tasks: I'll stick to the blue cardboard "codes" in that case :D

Thanks!

**Comment by daitj** [comment]
@peejii73 unfortunately i do not have any old devices to check, you could try to debugging via RootCloak. Looking for which command is Code App requesting, then you could block that command for Code app.

About the versioning, I couldn't make 1.1 version in Xposed Repo for some reason. It will stay like that until there is some updates to the app.

**Comment by peejii73** [comment]
Great, thanks for the info. I will dig into the RootCloak debug stuff then - maybe it'll reveal something.

Edit: Checked this. The only thing I got out from this is quite laconic:
"I/Xposed  (time): Mobile Token Package found".

<sigh>
