### ISSUE TITLE
Doesn't work with the latest RootCloak

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [themightydeity/XposedCodeApp#2]
This app doesn't work with RootCloak 2.0.1.

**Comment by daitj** [comment]
Are you sure RootCloak is active? RootCloak apparently has changed compatibility Xposed bridge version to 82 so RootCloak doesn't get activated at all (happened to my device as well). So it is no this apps issue. Make sure after you have RootCloak active to use proper keyword setting as mentioned in XposedCodeApp's description.

**Comment by Bec-de-Xorbin** [comment]
True. Thanks.
