### ISSUE TITLE
Edit description of XposedCodeApp module...

### ISSUE THREAD

**Issue by timuryn** [themightydeity/XposedCodeApp#3]
Hello,

First of all let me tell, thank you. Now I don't need unroot and root back again, each time I use nordea netbank service.

Secondly, could you edit part of [module's description](http://repo.xposed.info/module/com.binaydevkota.xposedcodeapp) from that:

Add Code app (com.nordea.mobiletoken) in App list(Add/Remove Apps) and find in the command list (Add/Remove Commands Hidden by RootCloak) of RootCloak.

to that:

Instruction:
1. Add Code app (com.nordea.mobiletoken) in App list(Add/Remove Apps).
2. Add the word **_find_** in the command list (Add/Remove Commands Hidden by RootCloak) of RootCloak.

With best regards,
timuryn

**Comment by daitj** [comment]
I have updated the app description in Xposed
