### ISSUE TITLE
Version 2 of the module, shows as 1.0 :(

### ISSUE THREAD

**Issue by timuryn** [themightydeity/XposedCodeApp#4]
Hello,

I've tried update module, also delete old version and download manually from [here](https://github.com/themightydeity/XposedCodeApp/releases/download/v1.1/XposedCodeApp.apk), but still version number stated 1.0

With best regards,
timuryn

**Comment by daitj** [comment]
Yeah there was some issue with versioning, will probably update it at some point. But just have the latest one from Xposed, it should be fine.
