### ISSUE TITLE
Nordea code app updated, RootCloak + XposedCodeApp does not work anymore.

### ISSUE THREAD

**Issue by villelappi** [themightydeity/XposedCodeApp#5]
Hi,

Nordea updated code app 14t. of June. Seems that root hiding doesn't work anymore.

I also tried to re-install RootCloak and XposedCodeApp.

 - Ville

**Comment by Enskan** [comment]
Hey, 
Same thing here, since about 14th of june Nordea codes recognises root. I also reinstalled Rootcloak and the ExposedApp. I the process i also tried the similar app "Nordea RootBypasser" which did not work either. 

Please help us soon :)

**Comment by Enskan** [comment]
Also found info in nordeas FAQ saying that "the new version of the code app reconises root better than the previous"

**Comment by tanty** [comment]
In my case, the nordea code apps has even started to crash consistently. I don't get to see if it recognizes root because it doesn't get to open any more :(

**Comment by villelappi** [comment]
Try NordeaRootBypasser version 1.1. It works with latest Nordea code app.

**Comment by daitj** [comment]
I am no longer maintaining this project, I use Magisk and systemless root in which you can hide root status. it works only on Android 5+
